from raw_data_compile import VdsaMicrotSNE

#creating tSNE interim data
compile_data=VdsaMicrotSNE()
compile_data.path_values_create(region_folder_position=6)
compile_data.gen_info_cleaner()
compile_data.coping_mech_cleaner()
compile_data.assests_liabs()
# compile_data.plotlist()
# # compile_data.family_comp()
# compile_data.landholding()
# compile_data.livestock()
# compile_data.farm_equip()
# compile_data.cons_durab()
# compile_data.stock_inv()
# compile_data.gender_decs_making()
# compile_data.gender_crop_cult()
# compile_data.info_ranking()
# compile_data.reliab_rank()
# compile_data.govt_assist()
# compile_data.crop_info_op()
# compile_data.cult_inputs()
# compile_data.food_exp()
# compile_data.nf_exp()
# compile_data.f_nf_exp()
# compile_data.fin_trans()
# compile_data.loans()
# compile_data.prod_sold()
# compile_data.sale_pur()
# compile_data.govt_dev_prog()
# compile_data.building()

