unmapped_activities = [
    'COLD STORAGE CHARGES',
    'CONSULTANT CHARGES',
    'CONSULTANT PAYMENT',
    'Crop Is Dead Due To Excess Water',
    'DERIBALI',
    'DIPPING',
    'DIPPING'
]

unmapped_activities = [
    'FALLOW',
    'FIELD CLEANING',
    'FIELD CLEANING-FENCE TRIMMING',
    'FIELD CLEANING-STEM BURRIED IN SOIL',
    'FIELD CLEANING-STEM BURRIED INTO SOIL',
    'FIELD CLEANING-UPROOTING',
    'FIELD CLEANING-UPROOTING THE LEMON PLANT',
    'FIELD PREPARATION AND MANURING',
    'FIELD PREPARATION',
    'FIELD PREPRATION',
    'FIELD PREPRATION AND FYM APPLICATION',
    'FIELD PREPRATION AND SEED SOWING',
    'FILLING OF PIT',
    'FILLING OF PITS',
    'FILLING OF PITS WITH FERTILIZER',
    'FINISHING',
    'FLOOD AFFECTED THE CROP',
    'GARDLING',
    'GI WIRE FOR FIXING THE ANGLES'
]


'No Operation'