import pandas as pd
import numpy as np
from pathlib import Path
from reducer import VdsaMicroReducer



class RankModelDataCreator(VdsaMicroReducer):

    """
    This class contains methods developed to generate processed datasets from certain high dimensionality data. Datasets created by this class of methods will be used in STATA for generating ranks. Ranks are generated by modelling the corresponding data columns on the household level cultivation.
    """

    def __init__(self):
        super().__init__()

        self.to_be_ranked_path=self.interim_path.joinpath('ranked')

        if not self.to_be_ranked_path.exists():
            self.to_be_ranked_path.mkdir(parents=True)
    
    def interim_files_path_create(self, tags:list, stage:str):
        """
        """
        


    def merged_data_creator(self, indep_tags:list, dep_tag:str):
        
        """
        A method to to create merged datasets between each of the indep_tags and dep_tag datasets. These merged datasets will be supplied to STATA to model and generate regression coeffcients and corresponsding ranks.
        Parameters:
        self: Inherits all the path structures defined in __init__.
        indep_tags: A lsit which calls for dataets which contains independent variables upon which the dependent variable will be regressed.
        dep_tag: A string value which calls for the dataset which conatins the dependent variable which will be regressed on the independent varibales.
        """




